apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: europe-central2-docker.pkg.dev/irio-2425-routing/irio-routing/routing
        name: worker
        ports:
        - containerPort: 8000
        args: ["worker:app"]
        env:
        - name: POD_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_PORT
          value: "8000"
